vich_uploader:
    db_driver: orm
    mappings:
       documents:
            uri_prefix: '%app.path.files_upload%'
            upload_destination: '%kernel.project_dir%/public/%app.path.files_upload%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'userId', transliterate: true }
            delete_on_update: false
            delete_on_remove: false